disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Keith Thomson"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/fishtank.png"
secondaryLogo = "img/fishtank.png"
description = "Keith Thomson - Cloud Engineer | Developer --- Professional Portfolio and Blog Site"
copyright = "Copyrighted ‚úèÔ∏è2024 Keith Thomson"

[author]
name = "üêß Keith Thomson"
email = "thomsonk930@gmail.com"
image = "/img/sophia-graduation-elementarySchool.jpeg"
imageQuality = 96
headline = "I'm only human"
bio = "I design and develop **Cloud-Native Solutions** that are scalable and efficent. I also provide Data Processing and Quality Assurance services, data labeling, migrations, database design, etc. __Let me prepare your data for Artificial Intelligence!__"
links = [
  { email = "mailto:thomsonk930@gmail.com" },
  { link = "https://whalelogic.io/" },
  #     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #     { apple = "https://www.apple.com" },
  #     { blogger = "https://username.blogspot.com/" },
  #     { bluesky = "https://bsky.app/profile/username" },
  #     { codepen = "https://codepen.io/username" },
  #     { dev = "https://dev.to/username" },
  #     { discord = "https://discord.gg/invitecode" },
  #     { dribbble = "https://dribbble.com/username" },
  #     { facebook = "https://facebook.com/username" },
  #     { flickr = "https://www.flickr.com/photos/username/" },
  #     { foursquare = "https://foursquare.com/username" },
  { github = "https://github.com/whalelogic" },
  #     { gitlab = "https://gitlab.com/username" },
  { google = "https://www.google.com/thomsonk930" },
  #     { hashnode = "https://username.hashnode.dev" },
  #     { instagram = "https://instagram.com/username" },
  #     { itch-io = "https://username.itch.io" },
  #     { keybase = "https://keybase.io/username" },
  #     { keyoxide = "https://keyoxide.org/URI" },
  #     { kickstarter = "https://www.kickstarter.com/profile/username" },
  #     { lastfm = "https://lastfm.com/user/username" },
  { linkedin = "https://linkedin.com/in/keith-t-146081322" },
  #     { mastodon = "https://mastodon.instance/@username" },
  #     { matrix = "https://matrix.to/#/URI" },
  { medium = "https://medium.com/username" },
  #     { microsoft = "https://www.microsoft.com/" },
  #     { orcid = "https://orcid.org/userid" },
  #     { patreon = "https://www.patreon.com/username" },
  #     { pinterest = "https://pinterest.com/username" },
  #     { reddit = "https://reddit.com/user/username" },
  #     { researchgate = "https://www.researchgate.net/profile/username" },
  #     { signal = "https://signal.me/#eu/userid" },
  #     { slack = "https://workspace.url/team/userid" },
  #     { snapchat = "https://snapchat.com/add/username" },
  #     { soundcloud = "https://soundcloud.com/username" },
  #     { spotify = "https://open.spotify.com/user/userid" },
  #     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #     { steam = "https://steamcommunity.com/profiles/userid" },
  #     { telegram = "https://t.me/username" },
  #     { threads = "https://www.threads.net/@username" },
  #     { tiktok = "https://tiktok.com/@username" },
  #     { tumblr = "https://username.tumblr.com" },
  #     { twitch = "https://twitch.tv/username" },
  #     { twitter = "https://twitter.com/username" },
  #     { x-twitter = "https://twitter.com/username" },
  #     { whatsapp = "https://wa.me/phone-number" },
  { youtube = "https://youtube.com/username" },
  #     { ko-fi = "https://ko-fi.com/username" },
  #     { codeberg = "https://codeberg.org/username"},
]
